"""Record facts about the built PDF so documents cannot assert them from memory.

Three of the four stale self-referential claims in this project were assertions a
document made about its own status: a compiled PDF that was not compiled, a
toolchain said to be absent, a branch said to be unpushed. The page count in
docs/PROPOSED_PR.md said 27 when the PDF had grown to 35.

The count is taken from the LaTeX engine's own log at build time rather than
re-derived later, and stored beside the SHA-256 of the PDF it describes. A test
compares that hash against the committed PDF, so stats that no longer describe
the current file fail rather than being believed.

Usage:  python -m analysis.record_build_stats <tectonic-log> <pdf>
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / "paper" / "build_stats.json"


def record(log_path: Path, pdf_path: Path) -> dict:
    log = log_path.read_text(errors="replace")
    pages = re.search(r"\b(\d+)\s+pages?\b", log)
    if not pages:
        raise SystemExit(f"no page count found in {log_path}")
    stats = {
        "pages": int(pages.group(1)),
        "overfull_boxes": len(re.findall(r"Overfull", log)),
        "underfull_boxes": len(re.findall(r"Underfull", log)),
        "latex_warnings": len(re.findall(r"LaTeX Warning", log)),
        "pdf_sha256": hashlib.sha256(pdf_path.read_bytes()).hexdigest(),
        "recorded_utc": datetime.now(timezone.utc).isoformat(),
        "note": "Generated by analysis/record_build_stats.py at build time. "
                "pdf_sha256 ties these figures to the file they describe; a test "
                "fails when the committed PDF no longer matches.",
    }
    OUTPUT.write_text(json.dumps(stats, indent=2) + "\n")
    return stats


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    s = record(Path(sys.argv[1]), Path(sys.argv[2]))
    print(f"recorded: {s['pages']} pages, {s['overfull_boxes']} overfull, "
          f"{s['latex_warnings']} warnings, sha {s['pdf_sha256'][:12]}")
